// flow-typed signature: c49659b9e10562d6998b77029cb84f04
// flow-typed version: <<STUB>>/chance_v^1.0.4/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chance'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'chance' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chance/chance' {
  declare module.exports: any;
}

declare module 'chance/dist/chance.min' {
  declare module.exports: any;
}

declare module 'chance/Gruntfile' {
  declare module.exports: any;
}

declare module 'chance/test/test.address' {
  declare module.exports: any;
}

declare module 'chance/test/test.basic' {
  declare module.exports: any;
}

declare module 'chance/test/test.company' {
  declare module.exports: any;
}

declare module 'chance/test/test.file' {
  declare module.exports: any;
}

declare module 'chance/test/test.finance' {
  declare module.exports: any;
}

declare module 'chance/test/test.geojson' {
  declare module.exports: any;
}

declare module 'chance/test/test.helpers' {
  declare module.exports: any;
}

declare module 'chance/test/test.misc' {
  declare module.exports: any;
}

declare module 'chance/test/test.mobile' {
  declare module.exports: any;
}

declare module 'chance/test/test.normal' {
  declare module.exports: any;
}

declare module 'chance/test/test.person' {
  declare module.exports: any;
}

declare module 'chance/test/test.regional' {
  declare module.exports: any;
}

declare module 'chance/test/test.text' {
  declare module.exports: any;
}

declare module 'chance/test/test.time' {
  declare module.exports: any;
}

declare module 'chance/test/test.web' {
  declare module.exports: any;
}

declare module 'chance/util/yob-to-json' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chance/chance.js' {
  declare module.exports: $Exports<'chance/chance'>;
}
declare module 'chance/dist/chance.min.js' {
  declare module.exports: $Exports<'chance/dist/chance.min'>;
}
declare module 'chance/Gruntfile.js' {
  declare module.exports: $Exports<'chance/Gruntfile'>;
}
declare module 'chance/test/test.address.js' {
  declare module.exports: $Exports<'chance/test/test.address'>;
}
declare module 'chance/test/test.basic.js' {
  declare module.exports: $Exports<'chance/test/test.basic'>;
}
declare module 'chance/test/test.company.js' {
  declare module.exports: $Exports<'chance/test/test.company'>;
}
declare module 'chance/test/test.file.js' {
  declare module.exports: $Exports<'chance/test/test.file'>;
}
declare module 'chance/test/test.finance.js' {
  declare module.exports: $Exports<'chance/test/test.finance'>;
}
declare module 'chance/test/test.geojson.js' {
  declare module.exports: $Exports<'chance/test/test.geojson'>;
}
declare module 'chance/test/test.helpers.js' {
  declare module.exports: $Exports<'chance/test/test.helpers'>;
}
declare module 'chance/test/test.misc.js' {
  declare module.exports: $Exports<'chance/test/test.misc'>;
}
declare module 'chance/test/test.mobile.js' {
  declare module.exports: $Exports<'chance/test/test.mobile'>;
}
declare module 'chance/test/test.normal.js' {
  declare module.exports: $Exports<'chance/test/test.normal'>;
}
declare module 'chance/test/test.person.js' {
  declare module.exports: $Exports<'chance/test/test.person'>;
}
declare module 'chance/test/test.regional.js' {
  declare module.exports: $Exports<'chance/test/test.regional'>;
}
declare module 'chance/test/test.text.js' {
  declare module.exports: $Exports<'chance/test/test.text'>;
}
declare module 'chance/test/test.time.js' {
  declare module.exports: $Exports<'chance/test/test.time'>;
}
declare module 'chance/test/test.web.js' {
  declare module.exports: $Exports<'chance/test/test.web'>;
}
declare module 'chance/util/yob-to-json.js' {
  declare module.exports: $Exports<'chance/util/yob-to-json'>;
}
